name: shop
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:


  flutter:
    sdk: flutter
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  provider: ^6.0.0
  cloud_firestore: ^2.5.1
  shared_preferences: ^2.0.7

  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/icons/
    - images/jackets/
    - images/trousers/
    - images/shoes/
    - images/t-shirts/

  fonts:
     - family: Pacifico
       fonts:
         - asset: fonts/Pacifico-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
