import 'package:flutter/material.dart';

const kProductsCollection = 'Products';
const kProductName = 'productName';
const kProductPrice = 'productPrice';
const kProductDescription = 'productDescription';
const kProductLocation = 'productLocation';
const kProductCategory = 'productCategory';
const KMainColor = Color(0xFFFFC12F);
const KSecondaryColor = Color(0xFFFFE6AC);
const kUnActiveColor = Color(0xFFC1BDB8);
const kJackets = "jackets";
const kTrousers = 'trousers';
const kTshert = 't-shirts';
const kShoes = 'shoes';
const kProductQuantity = 'Quantity';
const kOrders = "orders";
const kOrderDetails = 'orderDetails';
const kTotalPrice = "totalPrice";
const kAddress = "address";
